[[plugins]]
repo = 'Shougo/dein.vim'


# COLOR SCHEME
[[plugins]]
repo = 'w0ng/vim-hybrid'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'
hook_add = 'colorscheme PaperColor'


# SYNTAX HIGHLIGHT
[[plugins]] # Toml
repo = 'cespare/vim-toml'


# OTHER PLUGINS
[[plugins]] # status line
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode
    let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
            \ 'left': [ ['mode', 'paste'], ['readonly', 'filepath', 'modified'] ]
                \ },
        \ 'component_function':{'filepath': 'FilePath'}
        \ }

    function! FilePath()
        if winwidth(0) > 90
            return expand("%:s")
        else
            return expand("%:t")
        endif
    endfunction
'''

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
hook_add = '''
    set helplang=ja,en
'''

[[plugins]] #tag
repo = 'majutsushi/tagbar'
hook_add = 'noremap <silent><C-s> :TagbarToggle<CR>'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = 'noremap <silent><C-e> :NERDTreeToggle<CR>'


[[plugins]] # highlight word
repo = 't9md/vim-quickhl'
hook_add = '''
    nmap <Space>m <Plug>(quickhl-manual-this)
    xmap <Space>m <Plug>(quickhl-manual-this)

    nmap <Space>w <Plug>(quickhl-manual-this-whole-word)
    xmap <Space>w <Plug>(quickhl-manual-this-whole-word)

    nmap <Space>c <Plug>(quickhl-manual-clear)
    vmap <Space>c <Plug>(quickhl-manual-clear)

    nmap <Space>M <Plug>(quickhl-manual-reset)
    xmap <Space>M <Plug>(quickhl-manual-reset)

    nmap <Space>j <Plug>(quickhl-cword-toggle)
    nmap <Space>] <Plug>(quickhl-tag-toggle)
    map H <Plug>(operator-quickhl-manual-this-motion)
'''

[[plugins]] # change "()" colors
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1 
    let g:rainbow_conf = {
        \	'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick'],
        \	'ctermfgs': ['lightblue', 'lightyellow', 'lightcyan', 'lightmagenta'],
        \	'operators': '_,_',
        \	'parentheses': ['start=/(/ end=/)/ fold', 'start=/\[/ end=/\]/ fold', 'start=/{/ end=/}/ fold'],
        \	'separately': {
        \		'*': {},
        \		'tex': {
        \			'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/'],
        \		},
        \		'lisp': {
        \			'guifgs': ['royalblue3', 'darkorange3', 'seagreen3', 'firebrick', 'darkorchid3'],
        \		},
        \		'vim': {
        \			'parentheses': ['start=/(/ end=/)/', 'start=/\[/ end=/\]/', 'start=/{/ end=/}/ fold', 'start=/(/ end=/)/ containedin=vimFuncBody', 'start=/\[/ end=/\]/ containedin=vimFuncBody', 'start=/{/ end=/}/ fold containedin=vimFuncBody'],
        \		},
        \		'html': {
        \			'parentheses': ['start=/\v\<((area|base|br|col|embed|hr|img|input|keygen|link|menuitem|meta|param|source|track|wbr)[ >])@!\z([-_:a-zA-Z0-9]+)(\s+[-_:a-zA-Z0-9]+(\=("[^"]*"|'."'".'[^'."'".']*'."'".'|[^ '."'".'"><=`]*))?)*\>/ end=#</\z1># fold'],
        \		},
        \		'css': 0,
        \	}
        \}
'''

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]] # toggle comment
repo = 'tomtom/tcomment_vim'

